name: rpc_mongo_mapper
version: 0.1.3+1
description: >
  rpc_mongo_mapper is a package that allow you to easily provide CRUD operation to a class
  with rpc and store its representation inside mongodb
author: PLATEL Kevin <platel.kevin@gmail.com>
homepage: https://github.com/platelk/rpc_mongo_mapper
environment:
  sdk: ">=1.15.0 <2.0.0"
dependencies:
  rpc: "0.5.6"
  mongo_dart: "^0.2.5+1"
  amqp_rpc_binder: "^0.1.1"
  logging: "0.11.2"
dependency_overrides:
  logging: "0.11.2" # dart_amqp package depends of '>=0.9.3 <0.10.0'
